Repository wireapp/wire-ios-share-engine, pull requests merged in 2021-07, with the labels that each got.

#240 Feature: xcframework
  Cartfile
  Cartfile.private
  Cartfile.resolved
  Resources/Configurations/wire-ios-share-engine.xcconfig
  Resources/Configurations/zmc-config/ios-test-host.xcconfig
  Resources/Configurations/zmc-config/ios-test-target.xcconfig
  Resources/Configurations/zmc-config/ios.xcconfig
  Resources/Configurations/zmc-config/project-common.xcconfig
  WireShareEngine.xcodeproj/project.pbxproj
Labels: DO NOT MERGE

#248 [Feature] Propagate the file sharing feature
  Sources/SharingSession.swift
Labels: Feature request

#247 [Refactor] Feature configs
  Cartfile
  Cartfile.resolved
  Sources/SharingSession.swift
  WireShareEngineTests/BaseSharingSessionTests.swift
Labels: API breaker
